### ISSUE TITLE
More concise names

### ISSUE THREAD

**Issue by c42f** [FugroRoames/CoordinateTransformations.jl#11]
Typing (and reading) `BlahTransformation` is a pain, especially applied to the concrete types `AffineTransformation` and `LinearTransformation`.  Some contenders:

* `LinearMap` and `AffineMap` are pretty nice (might motivate a package name change?  `CoordinateMappings`?)
* `Linear` and `Affine` are short but `Linear` seems too generic.  (I personally don't like this)
* Using `*Tform` as in *AffineTransformations.jl* might make sense.  `LinearTform` and `AffineTform`?  A bit ugly, but very distinctive.

**Comment by andyferris** [comment]
I could live with `LinearMap` and `AffineMap` for transformations on vector-like objects.

We also have the names, `IdentityTransformation` and `ComposedTransformation` to consider, as well as `Transformation` and *CoordinateTransformations.jl*.

In general, when thinking about this, I think the API needs to be general enough to go beyond *coordinate* transformations. I'm imagining transforming one image into another image, or really any Julia object to any other Julia object, so long as the user can think of a use for the ability to do chaining, inverting, etc. While the word `Map` might make sense to linear algebra people, is it a good choice of word for images, sounds, or whatever?

**Comment by c42f** [comment]
Done!
