### ISSUE TITLE
Rotation examples seem to be broken

### ISSUE THREAD

**Issue by rdeits** [FugroRoames/CoordinateTransformations.jl#18]
I'm trying to follow along with the documentation from the readme, but it seems like the rotation examples are no longer working. The very first example in the quick start references `Rotation2D`, which does not appear to be defined in `Rotations.jl` or `CoordinateTransformations.jl`. Likewise, there doesn't seem to be any way to convert the `Rotation` type into a transform that CoordinateTransformations can use. 

Is there still a way to handle rotations with this package?

**Comment by rdeits** [comment]
It looks like rotations work when converted to `LinearMap` objects: 

```julia
julia> t = Translation(1, 2, 3.)
Translation(1.0,2.0,3.0)

julia> t2 = LinearMap(AngleAxis(pi/2, 0, 0, 1))
LinearMap(AngleAxis(1.5708, 0.0, 0.0, 1.0))

julia> compose(t, t2)
AffineMap(AngleAxis(1.5708, 0.0, 0.0, 1.0), [1.0,2.0,3.0])
```

**Comment by andyferris** [comment]
Right... no-one updated the README. Sorry about that.

**Comment by andyferris** [comment]
OK I've updated the README to be CoordinateTransformations 0.3 and Julia 0.5 friendly. If you are using Julia 0.4 then use *FixedSizeArrays* and the older interface of *Rotations* as a backend.

If the README make sense please feel free to close the issue, or otherwise suggest improvements. I hope that helps!

**Comment by rdeits** [comment]
Yes, that's great, thank you! I'm excited to try out the package in more depth.

**Comment by andyferris** [comment]
Great, I'll tag a release since I made a couple of new methods while I was at it.
