### ISSUE TITLE
Access fields of AffineMap

### ISSUE THREAD

**Issue by jw3126** [FugroRoames/CoordinateTransformations.jl#37]
Is there a recommended way to access the linear / constant part of an `AffineMap`?
The actual fieldnames `m,v` sound pretty private. Also they can't be used in generic code that should work with any `AbstractAffineMap`. Some things I would like to do that require them:
```julia
eltype(mymap.m)
size(mymap.m)
function (am::AbstractAffineMap)(r::MyRay)
    o = am(r.origin)
    d = am.m * r.direction
    MyRay(o, d)
end
```

**Comment by jw3126** [comment]
Mhh I realize that inventing a type for e.g. the constant part of `Linear{MyExoticMatrixType}` is tricky.

**Comment by andyferris** [comment]
It's an immutable type - please feel free to access the fields!

The names are that way just because I was too lazy to think of better names. Happy to hear suggestions to make them seem more friendly.

Originally we had grand plans to e.g. convert any (non-linear, differentiable) map to an affine map approximation around a point, and to make it easy to get the translation and linear components from affine maps. We can support an interface for getting these components from `AffineMap`, say a pair of functions rather than using field access, if that seems preferable.

**Comment by jw3126** [comment]
I usually prefer getter functions since it is easier to extend them for new types. I also find it hard to come up with a nice name:

* matrix: linear
* vector: translation, offset

**Comment by jw3126** [comment]
I could provide a PR that renames these fields into `linear` and `translation` and exports access functions with the same name. What do you think?

**Comment by andyferris** [comment]
Honestly, with the `getproperty` and `setproperty!` methods in Julia v0.7/v1.0 the idea of using `.` being private isn't really so relevant anymore, and there's no reason why `transform.linear` can't be seen an "external interface" that we want people to use. Consider the new `eig(matrix).values` (I think that's right) and so-on - similar syntax is coming to `Base`, `LinearAlgebra`, etc.

Do you think simply renaming `m` and `v` into something more readable (I like `linear` and `translation` btw) would be sufficient? (I would certainly welcome such a PR!)

**Comment by jw3126** [comment]
Yeah renaming the fields is a step forward. One inconvenience at the moment is that to define how custom objects transform you often need to overload three functions:
```julia
 (am::AffineMap)(r::MyRay)
 (am::LinearMap)(r::MyRay)
 (am::Translation)(r::MyRay)
```
and the implementation will be redundant. One approach would be to have getters that belong to the interface of `AbstractAffineMap`. Another would be to have
```julia
 (am::AffineMap)(obj) = LinearMap(am.linear)(Translation(am.translation)(obj))
```
Then there would be no redundancy, just
```julia
 (am::LinearMap)(r::MyRay)
 (am::Translation)(r::MyRay)
```
OTOH its not the end of the world to have this code duplication.

**Comment by andyferris** [comment]
Right. We could even deprecate `AffineMap` entirely and just use compositions of `LinearMap` and `Translation` (or make an `affine` function to create this).

I think `AffineMap` was partly implemented to make sure all compositions of linear maps and translations were eagerly joined together. We'd just need a convention of what order `Translation` and `LinearMap` take under `∘`.

**Comment by jw3126** [comment]
I think there is only one reasonable composition order. The usual formular `(g ∘ f)(x) = g(f(x))` must hold. If `g,f` are affine maps they should not be magically swapped.

An `affine` convenience function sounds good. I think it should be
`affine(l, t) = Translation(t)  ∘ LinearMap(l)`
rather then
`affine(l, t) = LinearMap(l)  ∘ Translation(t) `
for a couple of reasons (Unfortunately I used the latter flawed formular in my post above). The most convincing for me is:

You can express every affine map between two vector spaces as `Translation(t)  ∘ LinearMap(l)`, but not as 
`LinearMap(l)  ∘ Translation(t)`. To see this look at transforms from a low dimensional space to a high dimensional space. As an extreme case take transforms from the zero vector space to another vector space `V` . Then the set of affine maps are given by `0 -> v for v in V`, but you can only express `0 -> 0` in the latter way.

**Comment by andyferris** [comment]
> The usual formula `(g ∘ f)(x) = g(f(x))` must hold

We made a very concious design goal for us to be able to create long chains of e.g. small rotations and translations, and remain efficient. You can just take your current (affine) transformation state and translate and/or rotate it, and the type won't change and the representation won't grow.

**Comment by andyferris** [comment]
So that equality holds approximately true, up to floating-point error.

**Comment by jw3126** [comment]
Yeah sorry, I meant up to finite precission issues.

**Comment by jw3126** [comment]
The post was really only about composition order.

**Comment by andyferris** [comment]
Right! It has to behave in the way you specify the order, obviously. The way we implement that should be an invisible detail.

**Comment by jw3126** [comment]
What do you think about replacing
https://github.com/FugroRoames/CoordinateTransformations.jl/blob/66de0b2c96e8ee7f35661e6f0f68291a5cc34a25/src/affine.jl#L103-L105
by 
```julia
function (trans::AffineMap)(x)
     l = LinearMap(trans.linear)
     t = Translation(trans.translation)
     t(l(x))
end 
```
This way
* User objects must only implement `(t::Translation)(obj::Obj)` and `(l::LinearMap)(obj::Obj)`.
* It is not as extreme as deprecating `AffineMap`
* Long transform chains are still eagerly boiled down to a single affine map

One thing I am not sure about is if the compiler is smart enough to elide the `LinearMap` and `Translation` construction if e.g. x is just a vector. If you are interested, I can benchmark it.

**Comment by andyferris** [comment]
> I am not sure about is if the compiler is smart enough to elide the LinearMap and Translation construction

Yes, this was it. On v0.7 the compiler will easily elide the heap allocations and we are golden.

Can we put this in the "lets definitely do this in a month or so" bucket? I want to make sure there is at least one release of this package that works on v0.6 and v1.0 with no deprecations or performance caveats.

**Comment by jw3126** [comment]
Sure! My problem was not about heap allocations, but even if everything is bitstype you get some overhead by julia still constructing the `LinearMap` on the stack. Interestingly there is no more trace of `Translation`, just `LinearMap` pops up in the `@code_llvm`. On `v0.6` this degrades performance in the 3D case from 7ns to 11ns. We can revisit this on `v0.7` in a month or so.

**Comment by andyferris** [comment]
Cool. Can you share your benchmark code?

**Comment by jw3126** [comment]
Sure!
```julia
using CoordinateTransformations
using StaticArrays
using BenchmarkTools


function apply_lt(trans::AffineMap, x)
     l = LinearMap(trans.m)
     t = Translation(trans.v)
     t(l(x))
end

apply_master(trans,x) = trans(x)

m = @SMatrix randn(3,3)
v = @SVector randn(3)
am = AffineMap(m,v)
display(@benchmark apply_master($am, $v))
display(@benchmark apply_lt($am, $v))
@code_llvm apply_lt(am, v)
```
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     7.472 ns (0.00% GC)
  median time:      7.474 ns (0.00% GC)
  mean time:        7.967 ns (0.00% GC)
  maximum time:     103.006 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     9.275 ns (0.00% GC)
  median time:      9.278 ns (0.00% GC)
  mean time:        10.009 ns (0.00% GC)
  maximum time:     83.336 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999


define void @julia_apply_lt_63506(%SArray.63* noalias nocapture sret, %AffineMap* nocapture readonly dereferenceable(96), %SArray.63* nocapture readonly dereferenceable(24)) #0 !dbg !5 {
top:
  %3 = alloca %SArray.63, align 8
  %l = alloca %LinearMap, align 8
  %.sroa.0.0..sroa_cast3 = bitcast %AffineMap* %1 to i8*
  %l1415 = bitcast %LinearMap* %l to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %l1415, i8* %.sroa.0.0..sroa_cast3, i64 72, i32 1, i1 false)
  call void @julia_LinearMap_63396(%SArray.63* noalias nocapture nonnull sret %3, %LinearMap* nocapture nonnull readonly %l, %SArray.63* nocapture nonnull readonly %2)
  %4 = getelementptr inbounds %SArray.63, %SArray.63* %3, i64 0, i32 0, i64 0
  %5 = getelementptr inbounds %AffineMap, %AffineMap* %1, i64 0, i32 1, i32 0, i64 0
  %6 = load double, double* %4, align 8
  %7 = load double, double* %5, align 8
  %8 = fadd double %6, %7
  %9 = getelementptr inbounds %SArray.63, %SArray.63* %3, i64 0, i32 0, i64 1
  %10 = getelementptr inbounds %AffineMap, %AffineMap* %1, i64 0, i32 1, i32 0, i64 1
  %11 = load double, double* %9, align 8
  %12 = load double, double* %10, align 8
  %13 = fadd double %11, %12
  %14 = getelementptr inbounds %SArray.63, %SArray.63* %3, i64 0, i32 0, i64 2
  %15 = getelementptr inbounds %AffineMap, %AffineMap* %1, i64 0, i32 1, i32 0, i64 2
  %16 = load double, double* %14, align 8
  %17 = load double, double* %15, align 8
  %18 = fadd double %16, %17
  %"#temp#.sroa.0.sroa.0.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx" = getelementptr inbounds %SArray.63, %SArray.63* %0, i64 0, i32 0, i64 0
  store double %8, double* %"#temp#.sroa.0.sroa.0.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx", align 8
  %"#temp#.sroa.0.sroa.2.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx12" = getelementptr inbounds %SArray.63, %SArray.63* %0, i64 0, i32 0, i64 1
  store double %13, double* %"#temp#.sroa.0.sroa.2.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx12", align 8
  %"#temp#.sroa.0.sroa.3.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx13" = getelementptr inbounds %SArray.63, %SArray.63* %0, i64 0, i32 0, i64 2
  store double %18, double* %"#temp#.sroa.0.sroa.3.0.#temp#.sroa.0.0..sroa_cast1.sroa_idx13", align 8
  ret void
}
```
