### ISSUE TITLE
Should transform() be call()?

### ISSUE THREAD

**Issue by c42f** [FugroRoames/CoordinateTransformations.jl#4]
I'm wondering whether there's any advantage to having `transform()` as a named method distinct from `call()` (or whatever `call` is now called in 0.5)?

Syntactically there's not much in it, other than a win in brevity:

```julia
(a ∘ b ∘ c)(x)
# vs
transform(a ∘ b ∘ c, x)

T(x)
# vs
transform(T,x)
```

Semantically, using call seems totally consistent with the meaning of `call` for normal functions.

Are there any downsides?

**Comment by c42f** [comment]
One downside is the new lack of call overloading on abstract types (JuliaLang/julia#14919)

In 0.4, trying this change out is as simple as adding

```julia
Base.call(trans::AbstractTransformation, x) = transform(trans, x)
```

but there's no equivalent in 0.5 :-/

**Comment by andyferris** [comment]
> Base.call(trans::AbstractTransformation, x) = transform(trans, x)

I think I actually had this code in a previous version. I removed it purely because of JuliaLang/julia#14919.

I'm thinking "call" should be pretty clear here, assuming one uses sensible identifiers for the transformation instances.

```julia
polar_from_cartesian = PolarFromCartesian()
polar = polar_from_cartesian(Vec(1.0, 2.0))
```

PS - this makes me wonder, should singleton transformations have exported instances?

**Comment by andyferris** [comment]
I'm thinking we should completely remove `transform()` and just use call.

**Comment by c42f** [comment]
Definitely, call is the way to go here I think.

**Comment by andyferris** [comment]
I just thought of something - to make a new Julia object, we either use a constructor (wtih call) or the `convert` function.

Our transformations are in some ways super-constructors. They include some of the information needed to build an object, and sit waiting for the remaining information at which point they construct a new object.

The same might work for a "super-convert" using `transform`. Say I want to go from `Polar` to `Vector`, I could use

```julia
transform(Vector, CartesianFromPolar(), polar_point)
```

Or if I wanted a `Point` I could do

```julia
transform(Point, CartesianFromPolar(), polar_point)
```

And similarly for `Vec`, `Tuple` or any other valid type of Cartesian coordinate.

Alternatively, we could overload `convert` instead of using `transform`, or else define:

```julia
(::CartesianFromPolar){T}(::Type{T}, point::Polar) = ...
```

So many options...

**Comment by andyferris** [comment]
PS - previously knowing the output type wasn't a problem, but now we removed it from `AbstractTransformation`, it is a problem. Of course, for ambiguous situations, the type could be attached to the transformation, such as `CartesianFromPolar{Vec}()`.

**Comment by c42f** [comment]
Being able to specify the output container could be neat though I'd be inclined to wait until we see a solid use case.

**Comment by andyferris** [comment]
>  I'd be inclined to wait until we see a solid use case.

True. `CartesianFromPolar` isn't exactly crucial to my work. :)

**Comment by andyferris** [comment]
Should `transform` be deprecated or allowed?

**Comment by andyferris** [comment]
OK, I'm going through this and have noticed something interesting with the simple coordinate system transformations.

Now we do something like
```julia
# definition
(::SphericalFromCartesion)(x::Vec{3}) = ...

# usage
SphericalFromCartesian()(Vec(2.0, 3.0, 1.0))
```

which seems ridiculous compared to
```julia
# Constructor
(::Type{Spherical})(x::Vec{3}) = ...

# usage
Spherical(Vec(2.0, 3.0, 1.0))
```

One *main* advantage of the coordinate transformation is the composability and invertibility. The former could be gained by allowing `∘` accept constructors (types) as well, though we loose invertibility (which as I noted yesterday, we are kind of loosing that in other cases as well).

The other main advantage of coordinate transformation is doing pre-computation and keeping parameters across many transformations. But the singleton transformations seem a little "heavy", and I'm not sure how to resolve that.

**Comment by andyferris** [comment]
OK, to make `SphericalFromCartesian` we can write `Spherical ∘ Vec{3}` and it's inverse `Vec{3} ∘ Spherical` behaves just like `CartesianFromSpherical`. In both cases one of the calls will be a no-op, so there *shouldn't* be any run-time overhead.

To do this, we would need `Base.inv{T}(::Type{T}) = T`, which is a reasonably strange pun. Though there usually exists an "identity" (copy) constructor. Is that evil? Do the ends justify the means?

**Comment by c42f** [comment]
> Should transform be deprecated or allowed?

Deprecated I reckon.  `@deprecate` should work.

> we can write `Spherical ∘ Vec{3}` ...

I don't think this idea really extends cleanly in general: eg you often have several Cartesian coordinate systems, with `Point` used to represent points in each coordinate system.  There's no way to convert between systems via constructors in this case, because the coordinate system ID is not in the Point type parameters.

**Comment by andyferris** [comment]
Done in #8
