### ISSUE TITLE
Support for Lie Groups and Algebras

### ISSUE THREAD

**Issue by jc211** [FugroRoames/CoordinateTransformations.jl#46]
I have a SLAM application where I want optimize for a transformation. I usually do this by representing the transformation using its lie algebra and subsequently finding the increment I need to add so that the cost function decreases. 

I have seen mentioned in multiple places that this library is designed with SLAM in mind however I can't find any mention of Lie groups in the code. Is what I'm asking for currently supported by some other means perhaps? i.e. can I derive the transformation, get an increment and stay on the transformation manifold.

Or is it perhaps that this functionality needs to be added? Or perhaps created as a separate package. I'm mainly looking for an alternative for the Sophus C++ package and wondering if it should live here.

**Comment by jc211** [comment]
I suppose the Rodrigues parameterization in Rotations.jl will get me through. Thanks for pointing the package out. That being said, I wonder if the way forward with regards to expressing nice mathematical transformations is through creating new packages to express SE3 and Sim3 just as you did with Rotations.jl

**Comment by c42f** [comment]
You could easily build a package which talks in the language of Lie Groups, and which uses the tools from Rotations and StaticArrays for the internal implementation. I'd be very interesting to know if there are concrete practical advantages to using a Lie Group / Lie Algebra formalism for this kind of optimization?

**Comment by jc211** [comment]
For my purposes the Jacobians are already worked out in terms of the Lie algebras. The only thing I really need is a way to go from the algebra to the group. That itself is trivial. I suppose my thinking is that the Lie Group/Algebra formalism would be nice as most papers use it to express their minimization problems.

**Comment by c42f** [comment]
You may find https://github.com/RoboticExplorationLab/DifferentialRotations.jl/issues/1 interesting.
